version: 0.2

env:
  variables:
    CLUSTER_NAME: "guvi-eks-cluster"
    REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies (kubectl, awscli, eksctl)..."
      - rm -f /usr/local/bin/kubectl
      - curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client
      - pip install awscli
  pre_build:
    commands:
      - echo "Configuring kubectl access"
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
  build:
    commands:
      - echo "Deploying manifests to EKS..."
      - kubectl apply -f deployment.yaml --validate=false
      - kubectl apply -f service.yaml --validate=false
  post_build:
    commands:
      - echo "Deployment successful ✅"

