version: 0.2

env:
  variables:
    CLUSTER_NAME: "guvi-eks-cluster"
    REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies (kubectl, awscli)..."
      - rm -f /usr/local/bin/kubectl
      - curl -o kubectl https://s3.us-west-1.amazonaws.com/amazon-eks/1.30.0/2024-09-26/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - sudo mv kubectl /usr/local/bin/
      - chmod +x /usr/local/bin/kubectl
      - /usr/local/bin/kubectl version --client
      - pip install awscli
  pre_build:
    commands:
      - echo "Configuring kubectl for cluster access"
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
  build:
    commands:
      - echo "Running deployment script..."
      - chmod +x scripts/deploy_to_eks.sh
      - ./scripts/deploy_to_eks.sh
  post_build:
    commands:
      - echo "✅ Deployment completed successfully"

